apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rtdlm

resources:
  - ../base
  - training-job.yaml
  - distributed-training.yaml
  - headless-service.yaml
  - pdb.yaml
